<?php 
$title = 'Add Sms Template';
$this->headTitle($title);
$form = $this->form;
//echo get_class($form);die;
$form->setAttribute('action', $this->url('sms', array('action' => 'add')));
$form->prepare();
?>
<div>
<?php
    echo $this->form()->openTag($form);
    echo $this->formHidden($form->get('id'));
    echo $this->formRow($form->get('sms_title'));
    echo $this->formRow($form->get('sms_temp')->setAttributes(array('col' => '50')));
    echo $this->formSubmit($form->get('submit'));
    echo $this->form()->closeTag();
?>
</div>

<script type='text/javascript'>
    $("#sms").validate({
        rules: {
            sms_title: {
                required: true,
            },
            sms_temp: {
                required: true,
            }
        },
        messages: {
            sms_title: "Please specify template title.",
            sms_temp: "Please specify template subject.",
       }
    });
</script>