<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
        <?php echo $this->headTitle($this->translate('B.L.K MEMORIAL OXFORD ENGLISH SCHOOL'))->setSeparator(' - ')->setAutoEscape(false) ?>
        <?php echo $this->render('layout/head.phtml') ?>
    </head>
    <body>
        <div class="header-bg">
            <div class="wrap"> 
                <div class="total-box">
                    <div class="total">
                        <div class="header_top">
                            <div class="menu">
                                <ul>
                                    <li><a href="<?php echo $this->url('home');?>">Home</a></li>
                                    <li><a href="<?php echo $this->url('events');?>">Events</a></li>
                                    <li class="active"><a href="<?php echo $this->url('about');?>">About Us</a></li>
                                    <li><a href="<?php echo $this->url('contact');?>">Contact Us</a></li>
<!--                                    <li><a href="<?php //echo $this->url('login') ?>">Login</a></li>
                                    <li><a href="">Contact</a></li>-->
                                    <div class="clear"></div>
                                </ul>
                            </div>
                            <ul class="follow_icon">
                                <li><a href="#" style="opacity: 1;"><img src="images/fb.png" alt=""></a></li>
<!--							<li><a href="#" style="opacity: 1;"><img src="images/tw.png" alt=""></a></li>
                                <li><a href="#" style="opacity: 1;"><img src="images/rss.png" alt=""></a></li>-->
                            </ul>
                            <div class="clear"></div>
                        </div>
                        <div class="header-bottom">
                            <div class="logo">
                                <h1><a href="<?php echo $this->basePath()?>"><img width="100px;" src="../images/Oxford.png" />&nbsp;</a> </h1>
                               
                            </div>
                            <div class="logo-text">Oxford English School</div>
                            <div class="search">
                                <form>
                                    <input type="text" placeholder="search.." value="">
                                    <input type="submit"  value="">
                                </form>
                            </div>
                            <div class="clear"></div> 
                        </div>
                    </div>	
                </div>
            </div>
        </div>
        <div class="banner-box">
            <?php echo $this->content; ?>
           
            <?php echo $this->render('layout/footer.phtml') ?>
        </div>
    </body>
</html>



