<div class="wrap">
    <div class="main-top">
        <div class="main">
            <div class="section group">
                <div class="col span_2_of_3">
                    <div class="contact-form">
                        <h3>Contact Us</h3>
                        <form method="post" action="<?php echo $this->url('contact',array('action'=>'post'))?>">
                            <div>
                                <span><label class="required" for="userName">Name</label><em>*</em></span>
                                <span><input name="userName" type="text" class="textbox"></span>
                            </div>
                            <div>
                                <span><label>Mobile Number</label></span>
                                <span><input name="mobilenumber" type="text" class="textbox"></span>
                            </div>
                            <div>
                                <span><label class="required" for="userEmail">E-Mail</label><em>*</em></span>
                                <span><input name="userEmail" type="text" class="textbox"></span>
                            </div>
                            <div>
                                <span><label for="userMsg">Comments and questions</label><em>*</em></span>
                                <span><textarea name="userMsg"> </textarea></span>
                            </div>
                            <div>
                                <span><input type="submit" value="Submit"></span>
                            </div>
                        </form>
                    </div>
                </div>
                <div class="col span_1_of_3">

                    <div class="company_address">
                        <h3>Address</h3>
                        <p>Kazzakpura, Varanasi,</p>
                        <p>Uttar Pradesh 221001,</p>
                        <p>India</p>
                        <p>Phone:(+91) 093358 81299</p>
                        <p>Fax: (000) 000 00 00 0</p>
                        <p>Email: <span>info[at]mycompany.com</span></p>
                        <p>Follow on: <span>Facebook</span>, <span>Twitter</span></p>
                    </div>
                </div>
                <div class="clear"></div> 
            </div>
            <div class="map">
                <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3606.2350401520666!2d83.02657531431977!3d25.329892832521605!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x398e2df283b4205f%3A0x3d5fc3a92931a755!2sOxford+English+School!5e0!3m2!1sen!2sin!4v1445529927955" width="100%" height="175" frameborder="0" scrolling="no" marginheight="0" marginwidth="0"></iframe><br><small><a href="https://www.google.co.in/maps/place/Oxford+English+School/@25.3298928,83.0265753,17z/data=!3m1!4b1!4m2!3m1!1s0x398e2df283b4205f:0x3d5fc3a92931a755?hl=en" style="color:#666;text-align:left;font-size:12px">View Larger Map</a></small>
            </div>
        </div>
    </div>
</div>
<div class="main-bottom">
    <div class="wrap">
        <div class="content-bottom">
            <div class="col_1_of_3 span_1_of_3">
                <h3>Welcome to our Centre!</h3>
                <p class="desc2"><strong>Lorem ipsum dolor sit amet conse ctetur adipisicing elit, sed do eiusmod tempor incididunt.</strong></p>
                <p class="desc1">Lorem ipsum dolor sit amet conse ctetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequ.</p>
                <p class="desc1">Lorem ipsum dolor sit amet conse ctetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut conse ctetur adipisicing elit, sed do eiusmod conse ctetur adipisicing elit, sed do eiusmod</p>
                <a href="#" class="btn btn-primary"><span>Read more</span><img src="images/more_arrow.png" alt=""></a>
            </div>
            <div class="col_1_of_3 span_1_of_3">
                <h3>Teaching Support</h3>
                <ul class="dishes_list">
                    <li><a href="#">Consectetur adipisicing elit</a></li>
                    <li><a href="#">Sed do eiusmod tempor incididunt</a></li>
                    <li><a href="#">Labore et dolore magna aliqua.</a></li>
                    <li><a href="#">Sed do eiusmod tempor Dolore</a></li>
                    <li><a href="#">Abore et dolore magna Dolore elit</a></li>
                    <li><a href="#">Incididunt ut labore et dolore</a></li>
                    <li><a href="#">Incididunt ut labore et dolore</a></li>
                    <li class="last"><a href="#">Adipisicing elit, sed do eiusmod</a></li>
                    <div class="clear"> </div>
                </ul>
                <a href="#" class="btn btn-primary1"><span>Read more</span><img src="images/more_arrow.png" alt=""></a>
            </div>
            <div class="col_1_of_3 span_1_of_3">
                <h3>Latest News</h3>
                <div class="latest-news-grid">
                    <div class="latest-news-pic">
                        <img src="images/pic.jpg" title="imag-name">
                    </div>
                    <div class="latest-news-info">
                        <a href="#">Jan 21.01.2013</a>
                        <p class="desc1">Lorem ipsum dolor sit amet conse ctetur adipisicing elit, sed do eiusmod tempor</p>
                    </div>
                    <div class="clear"> </div>
                </div>
                <div class="latest-news-grid">
                    <div class="latest-news-pic">
                        <img src="images/pic1.jpg" title="imag-name">
                    </div>
                    <div class="latest-news-info">
                        <a href="#">Jan 21.01.2013</a>
                        <p class="desc1">Lorem ipsum dolor sit amet conse ctetur adipisicing elit, sed do eiusmod tempor</p>
                    </div>
                    <div class="clear"> </div>
                </div>
                <div class="latest-news-grid">
                    <div class="latest-news-pic">
                        <img src="images/pic2.jpg" title="imag-name">
                    </div>
                    <div class="latest-news-info">
                        <a href="#">Jan 21.01.2013</a>
                        <p class="desc1">Lorem ipsum dolor sit amet conse ctetur adipisicing elit, sed do eiusmod tempor</p>
                    </div>
                    <div class="clear"> </div>
                </div>
                <div class="latest-news-grid">
                    <div class="latest-news-pic">
                        <img src="images/pic3.jpg" title="imag-name">
                    </div>
                    <div class="latest-news-info">
                        <a href="#">Jan 21.01.2013</a>
                        <p class="desc1">Lorem ipsum dolor sit amet conse ctetur adipisicing elit, sed do eiusmod tempor</p>
                    </div>
                    <div class="clear"> </div>
                </div>
                <a href="#" class="btn btn-primary2"><span>Read more</span><img src="images/more_arrow.png" alt=""></a>
            </div>
            <div class="clear"></div> 
        </div>
    </div>
</div>