<?php echo $this->doctype(); ?>
<html lang="en" data-ng-app="myApp">
    <head>
        <?php echo $this->headTitle($this->translate('Oxford English School::Login'))->setSeparator(' - ')->setAutoEscape(false) ?>
        <?php echo $this->render('layout/header.phtml') ?>
    </head>
    <body> 
        <div class="header-bg">
            <div class="wrap"> 
                <div class="total-box">
                    <div class="total">
                        <div class="header_top">
                            <div class="menu">
                                <ul>
                                    <li><a href="index.html">Home</a></li>
                                    <li><a href="about.html">About</a></li>
                                    <li><a href="staff.html">Staff</a></li>
                                    <li class="active"><a href="<?php echo $this->url('login') ?>">Login</a></li>
                                    <li><a href="contact.html">Contact</a></li>
                                    <div class="clear"></div>
                                </ul>
                            </div>
                            <ul class="follow_icon">
                                <li><a href="#" style="opacity: 1;"><img src="images/fb.png" alt=""></a></li>
                                <li><a href="#" style="opacity: 1;"><img src="images/tw.png" alt=""></a></li>
                                <li><a href="#" style="opacity: 1;"><img src="images/rss.png" alt=""></a></li>
                            </ul>
                            <div class="clear"></div>
                        </div>
                        <div class="header-bottom">
                            <div class="logo">
                                <h2><a href="index.html">Guidance</a></h2>
                            </div>
                            <div class="clear"></div> 
                        </div>
                    </div>	
                </div>
            </div>
        </div>
       <div class="banner-box">
		<div class="main-bottom">
			<div class="wrap">
			<div class="content-bottom">
                            <div class="wrap-login"> 
				<div class="col_1_of_3 span_1_of_3">
					<div class="well">
                                        <?php echo $this->content; ?>
                                    </div>
				</div>
                            </div>
				<div class="clear"></div> 
			</div>
			</div>
		</div>
 
	    <?php echo $this->render('layout/footer.phtml') ?>
             <?php echo $this->inlineScript() ?> 
	</div>
    </body>
</html>