<div class="container-fluid">
    <?php echo $this->form()->openTag($form); ?>
   <div class="row">
             <div class="col-md-1"><label for="user_name"><?php echo sprintf($this->translate('User Name')) ?></label></div>

                    <div class="col-md-11 form-group"><?php echo $this->formRow($form->get('user_name')); ?></div>
         </div>
    <div class="row">
                    
        <div class="col-md-1"><label for="password"><?php echo sprintf($this->translate('Password')) ?></label></div>
                     <div class="col-md-11 form-group"><?php echo $this->formRow($form->get('user_name')); ?></div>
    </div>
    <div class="row">
                    
        <div class="col-md-1"><label for="password"><?php echo sprintf($this->translate('Change Password')) ?></label></div>
                     <div class="col-md-11 form-group"><?php echo $this->formRow($form->get('changepassword')); ?></div>
    </div>
                   
 <div class="row">
                    <?php echo $this->formSubmit($form->get('submit')); ?>
                </div>
    <?php echo $this->form()->closeTag(); ?>
               
</div>
