<div class="wrap">
    <div class="main-top">
        <div class="main">
            <div class="section group about_desc">
                <div class="col_1_of_3 grid_1_of_3">
                    <h2>Who We Are</h2>
                    <img src="images/pic4.jpg" alt=""/>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo.</p>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud.</p>
                </div>
                <div class="col_1_of_3 grid_1_of_3">
                    <h2>Success Stories</h2>
                    <div class="history-desc">
                        <div class="year"><p>1998 -</p></div>
                        <p class="history">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
                        <div class="clear"></div>
                    </div>
                    <div class="history-desc">
                        <div class="year"><p>2001 -</p></div>
                        <p class="history">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
                        <div class="clear"></div>
                    </div>
                    <div class="history-desc">
                        <div class="year"><p>2006 -</p></div>
                        <p class="history">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
                        <div class="clear"></div>
                    </div>
                    <div class="history-desc">
                        <div class="year"><p>2005 -</p></div>
                        <p class="history">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex.</p>
                        <div class="clear"></div>
                    </div>
                    <div class="history-desc">
                        <div class="year"><p>2004 -</p></div>
                        <p class="history">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitatio.</p>
                        <div class="clear"></div>
                    </div>
                </div>
                <div class="col_1_of_3 grid_1_of_3">
                    <h2>Our Services</h2>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p>

                    <ul>
                        <li>
                            <div class="numb_list red">1</div>
                            <div class="extra_wrapper">
                                <p class="link1"><a href="#">Lorem ipsum dolor sit amet</a></p>
                                <p>Eonsecteturdiingelulam a laoret eratacin itupis. Quisque Sed ut perspiciatis unde omnis iste lore natus error sit voluptatem accusantium doloremque.</p>
                            </div>
                        </li>
                        <li>
                            <div class="numb_list blue">2</div>
                            <div class="extra_wrapper">
                                <p class="link1"><a href="#">Praesent vestibulum molestie lacus</a></p>
                                <p>Eonsecteturdiingelulam a laoret eratacin itupis. Quisque Sed ut perspiciatis unde omnis iste lore natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque.</p>
                            </div>
                        </li>
                        <li>
                            <div class="numb_list green">3</div>
                            <div class="extra_wrapper">
                                <p class="link1"><a href="#">Sed ut perspiciatis unde omnis iste</a></p>
                                <p class="margin_1">Eonsecteturdiingelulam a laoret eratacin itupis. Quisque Sed ut perspiciatis unde omnis iste lore natus error sit voluptatem accusantium doloremque.</p>
                            </div>
                        </li>
                    </ul>
                </div>
                <div class="clear"></div>
            </div>
        </div>
    </div>
</div>
<div class="main-bottom">
    <div class="wrap">
        <div class="content-bottom">
            <div class="col_1_of_3 span_1_of_3">
                <h3>Welcome to our Centre!</h3>
                <p class="desc2"><strong>Lorem ipsum dolor sit amet conse ctetur adipisicing elit, sed do eiusmod tempor incididunt.</strong></p>
                <p class="desc1">Lorem ipsum dolor sit amet conse ctetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequ.</p>
                <p class="desc1">Lorem ipsum dolor sit amet conse ctetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut conse ctetur adipisicing elit, sed do eiusmod conse ctetur adipisicing elit, sed do eiusmod</p>
                <a href="#" class="btn btn-primary"><span>Read more</span><img src="images/more_arrow.png" alt=""></a>
            </div>
            <div class="col_1_of_3 span_1_of_3">
                <h3>Teaching Support</h3>
                <ul class="dishes_list">
                    <li><a href="#">Consectetur adipisicing elit</a></li>
                    <li><a href="#">Sed do eiusmod tempor incididunt</a></li>
                    <li><a href="#">Labore et dolore magna aliqua.</a></li>
                    <li><a href="#">Sed do eiusmod tempor Dolore</a></li>
                    <li><a href="#">Abore et dolore magna Dolore elit</a></li>
                    <li><a href="#">Incididunt ut labore et dolore</a></li>
                    <li><a href="#">Incididunt ut labore et dolore</a></li>
                    <li class="last"><a href="#">Adipisicing elit, sed do eiusmod</a></li>
                    <div class="clear"> </div>
                </ul>
                <a href="#" class="btn btn-primary1"><span>Read more</span><img src="images/more_arrow.png" alt=""></a>
            </div>
            <div class="col_1_of_3 span_1_of_3">
                <h3>Latest News</h3>
                <div class="latest-news-grid">
                    <div class="latest-news-pic">
                        <img src="images/pic.jpg" title="imag-name">
                    </div>
                    <div class="latest-news-info">
                        <a href="#">Jan 21.01.2013</a>
                        <p class="desc1">Lorem ipsum dolor sit amet conse ctetur adipisicing elit, sed do eiusmod tempor</p>
                    </div>
                    <div class="clear"> </div>
                </div>
                <div class="latest-news-grid">
                    <div class="latest-news-pic">
                        <img src="images/pic1.jpg" title="imag-name">
                    </div>
                    <div class="latest-news-info">
                        <a href="#">Jan 21.01.2013</a>
                        <p class="desc1">Lorem ipsum dolor sit amet conse ctetur adipisicing elit, sed do eiusmod tempor</p>
                    </div>
                    <div class="clear"> </div>
                </div>
                <div class="latest-news-grid">
                    <div class="latest-news-pic">
                        <img src="images/pic2.jpg" title="imag-name">
                    </div>
                    <div class="latest-news-info">
                        <a href="#">Jan 21.01.2013</a>
                        <p class="desc1">Lorem ipsum dolor sit amet conse ctetur adipisicing elit, sed do eiusmod tempor</p>
                    </div>
                    <div class="clear"> </div>
                </div>
                <div class="latest-news-grid">
                    <div class="latest-news-pic">
                        <img src="images/pic3.jpg" title="imag-name">
                    </div>
                    <div class="latest-news-info">
                        <a href="#">Jan 21.01.2013</a>
                        <p class="desc1">Lorem ipsum dolor sit amet conse ctetur adipisicing elit, sed do eiusmod tempor</p>
                    </div>
                    <div class="clear"> </div>
                </div>
                <a href="#" class="btn btn-primary2"><span>Read more</span><img src="images/more_arrow.png" alt=""></a>
            </div>
            <div class="clear"></div> 
        </div>
    </div>
</div>