<?php echo $this->doctype(); ?>
<html lang="en" ng-app="myapp">
<head>
   <?php echo $this->headTitle($this->translate('Oxford English School'))->setSeparator(' - ')->setAutoEscape(false) ?>
   <?php echo $this->render('layout/header.phtml') ?>
</head>
   <body ng-controller="">
<div class="header-bg">
	<div class="wrap"> 
		<div class="total-box">
				<div class="total">
					<div class="header_top">
				     	<div class="menu">
				     		<ul>
						    	<li><a href="index.html">Home</a></li>
						    	<li><a href="<?php //echo $this->url('dashboard') ?>">Dashboard</a></li>
						    	<li  class="active"><a href="<?php //echo $this->url('myaccount') ?>">My account</a></li>
						    	<li><a href="<?php echo $this->url('standard') ?>">Class</a></li>
                                                        <li><a href="<?php echo $this->url('student') ?>">Student</a></li>
                                                        <li><a href="<?php echo $this->url('sms') ?>">Template</a></li>
                                                        <li><a href="<?php echo $this->url('sms') ?>">Sms</a></li>
                                                        <li><a href="<?php echo $this->url('login', array('action' => 'logout'));?>">Logout</a></li>
						    	<div class="clear"></div>
			     			</ul>
				     	</div>
				     	<ul class="follow_icon">
							<li><a href="#" style="opacity: 1;"><img src="images/fb.png" alt=""></a></li>
							<li><a href="#" style="opacity: 1;"><img src="images/tw.png" alt=""></a></li>
							<li><a href="#" style="opacity: 1;"><img src="images/rss.png" alt=""></a></li>
						</ul>
		     			<div class="clear"></div>
		     	</div>
			     <div class="header-bottom">
					 <div class="logo">
						<h2><a href="index.html">Guidance</a></h2>
					 </div>
				<div class="clear"></div> 
				</div>
			</div>	
		</div>
	 </div>
</div>
       
<div class="banner-box">
		<div class="main-bottom">
			<div class="wrap">
			<div class="content-bottom">
                            <div class="wrap-login"> 
                                <h1 class="page-title" style="color:#000000;"><?php echo $this->heading; ?> </h1>
				<div class="col_1_of_3 span_1_of_3">
					<div class="well">
                                        <?php echo $this->content; ?>
                                    </div>
				</div>
                            </div>
				<div class="clear"></div> 
			</div>
			</div>
		</div>
 
	    <?php echo $this->render('layout/footer.phtml') ?>
             <?php echo $this->inlineScript() ?> 
	</div>
   </body>
</html>