<?php
$title = 'Add New Student';
$this->headTitle($title);
$form = $this->form;
//echo get_class($form);die;
$form->setAttribute('action', $this->url('student', array('action' => 'add')));
$form->setAttribute('class', 'form-horizontal');
$form->prepare();
?>
<div class="row">
    <div class="pull-right">
        <b>OR</b>
        <a href="<?php echo $this->url('student', array('action' => 'studentxls')); ?>">
            <img src="<?php echo $this->basePath('img/xls_oxford.png'); ?>"><br>
            <p style="margin:0px 0px 0px 84px;">Upload Student .xls Sheet</p>
        </a>
    </div>
    <div class="pull-left">
        <?php
        echo $this->form()->openTag($form);
        foreach ($form as $element) {
            // echo $this->formElement($element);
            echo $this->formElementErrors($form->get('class'), array('class' => 'input-error-message'));
        }
        ?>

        <?php echo $this->formHidden($form->get('id')); ?>
        <div class="form-group">
            <label for="form_class" class="col-sm-5 control-label"><?php echo $this->translate('Class Name') ?></label>
            <?php echo $this->formHidden($form->get('id')); ?>
            <div class="col-sm-7">
            <?php echo $this->formRow($form->get('class')); ?>
            </div>
        </div>
        <div class="form-group">
            <label for="form_student_name" class="col-sm-5 control-label"><?php echo $this->translate('Student Name') ?></label>
            <div class="col-sm-7">
<?php echo $this->formRow($form->get('student_name')); ?>
            </div>
        </div>

        <div class="form-group">
            <label for="form_father_name" class="col-sm-5 control-label"><?php echo $this->translate('Father Name') ?></label>
            <div class="col-sm-7">
<?php echo $this->formRow($form->get('father_name')); ?>
            </div>
        </div>

        <div class="form-group">
            <label for="form_mother_name" class="col-sm-5 control-label"><?php echo $this->translate('Mother Name') ?></label>
            <div class="col-sm-7">
<?php echo $this->formRow($form->get('mother_name')); ?>
            </div>
        </div>

        <div class="form-group">
            <label for="form_admission_no" class="col-sm-5 control-label"><?php echo $this->translate('Admission No') ?></label>
            <div class="col-sm-7">
<?php echo $this->formRow($form->get('admission_no')); ?>
            </div>
        </div>

        <div class="form-group">
            <label for="form_roll_no" class="col-sm-5 control-label"><?php echo $this->translate('Roll No') ?></label>
            <div class="col-sm-7">
<?php echo $this->formRow($form->get('roll_no')); ?>
            </div>
        </div>

        <div class="form-group">
            <label for="form_parent_mobile_1" class="col-sm-5 control-label"><?php echo $this->translate('Parent Mobile 1') ?></label>
            <div class="col-sm-7">
                <?php echo $this->formRow($form->get('parent_mobile_1')); ?>
            </div>
        </div>

        <div class="form-group">
            <label for="form_parent_mobile_2" class="col-sm-5 control-label"><?php echo $this->translate('Parent Mobile 2') ?></label>
            <div class="col-sm-7">
                <?php echo $this->formRow($form->get('parent_mobile_2')); ?>
            </div>
        </div>

        <div class="form-group">
            <div class="col-sm-offset-5 col-sm-7">
<?php echo $this->formSubmit($form->get('submit')); ?>
            </div>
        </div>
                <?php echo $this->form()->closeTag();
                ?>
    </div>
</div>
<script type='text/javascript'>
    $.validator.addMethod("valueNotEquals",function(value,element,arg){return arg!=value;},"Value must not equal arg.");
    $("#student").validate({
        rules: {
            class: {
                valueNotEquals:"0",
            },
            student_name: {
                required: true,
            },
            // compound rule
            father_name: "required",
            admission_no: {
                required: true,
                number: true
            },
            roll_no: {
                required: true,
                number: true
            },
            parent_mobile_1: "required",
        },
        messages: {
            student_name: "Please specify student name.",
            father_name: "Please specify father name.",
            class: {valueNotEquals:"Select any one Class."}
        }
    });
</script>