<?php
$title = 'Student Class-Wise Detail';
$this->headTitle($title);
$form = $this->form;
$form->setAttribute('action', $this->url('student', array('action' => 'studentclasswise')));
$form->setAttribute('method', 'post');
$form->setAttribute('id', 'standard');
$form->setAttribute('name', 'standard');
$form->prepare();
echo $this->form()->openTag($form);
echo $this->formRow($form->get('class'));
echo $this->form()->closeTag();
?>
     <table class="table table-bordered table-striped">
    <thead>
   
        <tr>
            <th>Roll</th>
            <th>Adm.No.</th>
            <th>Student&nbsp;Name</th>
            <th>Mobile1</th>
            <th>Mobile2</th>
            <th>Father&nbsp;Name</th>
            <th>Mother&nbsp;Name</th>
            <th>Class</th>
            <th>Action</th>
        </tr>
        </thead>
        <tbody>
            <?php 
            if(sizeof($student) > 0):
            foreach ($student as $object)://print_r($object);die;?>
            <tr>
                <td><a href=""><?php echo $object->roll_no; ?></a></td>
                <td><a href="<?php ?>"><?php echo $object->admission_no; ?></a></td>
                <td><a href="<?php ?>"><?php echo $object->student_name; ?></a></td>
                <td><a href="<?php ?>"><?php echo $object->parent_mobile_1; ?></a></td>
                <td><a href="<?php ?>"><?php echo $object->parent_mobile_2; ?></a></td>
                <td><a href="<?php ?>"><?php echo $object->father_name; ?></a></td>
                <td><a href="<?php ?>"><?php echo $object->mother_name; ?></a></td>
                <td><a href="<?php ?>"><?php echo $object->class; ?></a></td>
                <td><a href="<?php echo $this->url('student', array('action' => 'edit', 'id' => $object->id)); ?>" style="text-decoration:none;">Edit</a></td>
                <td><a href="<?php echo $this->url('student', array('action' => 'delete', 'id' => $object->id)); ?>" onclick="return confirm( & #39; Are you sure you want to delete this class? & #39; );" style="text-decoration:none;">Delete</a></td>                     
            </tr>
            <?php endforeach; 
            else:?>
                <tr>
                    <td colspan="9"><center><a href="<?php echo $this->url('student', array('action' => 'add')); ?>" style="text-decoration:none;"><?php echo $this->translate('No Records available!') ?></a></center></td>
                </tr>
            <?php endif;
            ?>
        </tbody>
    </table>
<script type="text/javascript">
jQuery( document ).ready(function( $ ) {
  // Code that uses jQuery's $ can follow here.
      var s1 = $('#form_class');

        s1.on('change', function() {

            $('#standard').submit();

        });
});
</script>